- hosts: k8s_cluster
  gather_facts: true
  become: yes
  roles:
    - role: docker

- hosts: k8s_cluster
  gather_facts: true
  become: yes
  roles:
    - role: k8s

- hosts: master[0]
  gather_facts: true
  become: yes
  roles:
    - role: master

- hosts: master[0]
  gather_facts: true
  become: yes
  roles:
    - role: calico

- hosts: node
  gather_facts: yes
  become: yes
  roles:
    - role: node

- hosts: master[0]
  become: true
  roles:
    - role: helm

- hosts: master[0]
  become: true
  roles:
    - role: metallb

- hosts: master[0]
  become: true
  roles:
    - role: persistentvolume

- hosts: master[0]
  become: true
  roles:
    - role: portainer