- hosts: k8s_cluster
  gather_facts: true
  tasks:
  - name: Install Docker and K8s on Master and worker
    become: yes
    shell: |
            apt install docker.io -y
            apt install apt-transport-https curl -y
            curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add
            echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list
            apt update
            apt install -y kubeadm=1.23.17-00 kubelet=1.23.17-00 kubectl=1.23.17-00 kubernetes-cni=1.1.1-00
            apt-mark hold kubelet kubeadm kubectl

- hosts: master
  gather_facts: true
  tasks:
  - name: Install Calico on Master
    become: yes
    shell: |
            kubeadm init --pod-network-cidr={{ pod_cidr }}
            mkdir -p $HOME/.kube
            cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
            chown $(id -u):$(id -g) $HOME/.kube/config
            kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.1/manifests/tigera-operator.yaml
            curl -s -o /tmp/custom-resources.yaml https://raw.githubusercontent.com/projectcalico/calico/v3.25.1/manifests/custom-resources.yaml
            sed -i "s@cidr: 192.168.0.0/16@cidr: {{ pod_cidr }}@g" /tmp/custom-resources.yaml
            kubectl create -f /tmp/custom-resources.yaml
            rm -f /tmp/custom-resources.yaml
  
  - name: Install MetalLB
    become: yes
    shell: kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.9/config/manifests/metallb-native.yaml

  - name: Get the token for joining the worker nodes
    become: yes
    shell: kubeadm token create --print-join-command
    register: kubernetes_join_command

  - name: Print Join Command
    debug:
      msg: "{{ kubernetes_join_command.stdout }}"

  - name: Copy join command to local file.
    become: yes
    local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777
  
- hosts: node
  gather_facts: yes
  tasks:
  - name: Copy join command from Ansiblehost to the worker nodes.
    become: yes
    copy:
      src: /tmp/kubernetes_join_command
      dest: /tmp/kubernetes_join_command
      mode: 0777

  - name: Join the Worker nodes to the cluster.
    become: yes
    command: sh /tmp/kubernetes_join_command
    register: joined_or_not