- name: Add portainer helm repo
  command: helm repo add portainer https://portainer.github.io/k8s/

- name: Update Repo
  command: helm repo update

- name: Install Portainer
  shell: |
          helm upgrade --install --create-namespace -n portainer portainer portainer/portainer \
          --set service.type=LoadBalancer \
          --set tls.force=true \
          --set persistence.storageClass=local-path