- name: kubeadm init on first Master
  shell: |
          kubeadm init --pod-network-cidr={{ pod_cidr }}
          mkdir -p $HOME/.kube
          cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
          chown $(id -u):$(id -g) $HOME/.kube/config

- name: Get the token for joining the worker nodes
  shell: kubeadm token create --print-join-command
  register: kubernetes_join_command

- name: Print Join Command
  debug:
    msg: "{{ kubernetes_join_command.stdout }}"

- name: Copy join command to local file.
  local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777